{ pkgs }: {
  deps = [
    pkgs.haskellPackages.HJavaScript
    pkgs.nodePackages.ijavascript
    pkgs.nodePackages_latest.ijavascript
    pkgs.perl534Packages.TemplatePluginJavaScript
    pkgs.perl536Packages.TemplatePluginJavaScript
    pkgs.perlPackages.TemplatePluginJavaScript
    pkgs.haskellPackages.netwire-input-javascript
    pkgs.haskellPackages.language-javascript
    pkgs.vimPlugins.vim-javascript-syntax
    pkgs.haskellPackages.language-javascript_0_7_0_0
    pkgs.haskellPackages.gi-javascriptcore
    pkgs.emacsPackages.frontside-javascript
    pkgs.haskellPackages.webkit-javascriptcore
    pkgs.vimPlugins.vim-javascript
    pkgs.haskellPackages.webkit2gtk3-javascriptcore
    pkgs.haskellPackages.fwgl-javascript
    pkgs.haskellPackages.yi-mode-javascript
    pkgs.haskellPackages.webkitgtk3-javascriptcore
    pkgs.tree-sitter-grammars.tree-sitter-javascript
    pkgs.perl534Packages.JavaScriptValueEscape
    pkgs.perl534Packages.JavaScriptMinifierXS
    pkgs.perl536Packages.JavaScriptValueEscape
    pkgs.perlPackages.JavaScriptMinifierXS
    pkgs.perl536Packages.JavaScriptMinifierXS
    pkgs.perlPackages.JavaScriptValueEscape
    pkgs.haskellPackages.javascript-extras
    pkgs.nodePackages_latest.javascript-typescript-langserver
    pkgs.nodePackages.javascript-typescript-langserver
    pkgs.haskellPackages.javascript-bridge
    pkgs.emacsPackages.diffsync
    pkgs.emacsPackages.auto-complete
    pkgs.python310Packages.pytest-metadata
    pkgs.vcluster
    pkgs.rPackages.mlr3db
    pkgs.xss-lock
    pkgs.octavePackages.io
    pkgs.log4jcheck
    pkgs.haskellPackages.patat
    pkgs.rPackages.galts
    pkgs.rPackages.RaggedExperiment
    pkgs.gnomeExtensions.undecorate
    pkgs.rst2html5
    pkgs.quicklispPackagesSBCL.cl-html5-parser
    pkgs.haskellPackages.bamboo-theme-mini-html5
    pkgs.quicklispPackages.cl-html5-parser
    pkgs.haskellPackages.diagrams-html5
    pkgs.rPackages.html5
    pkgs.haskellPackages.google-html5-slide
    pkgs.quicklispPackagesClisp.cl-html5-parser
    pkgs.lispPackages.cl-html5-parser
    pkgs.emacsPackages.ox-html5slide
    pkgs.home-assistant-component-tests.html5
    pkgs.html5validator
    pkgs.emacsPackages.html5-schema
    pkgs.haskellPackages.html5-entity
    pkgs.python39Packages.html5-parser
    pkgs.python310Packages.html5lib
    pkgs.python39Packages.html5lib
    pkgs.python310Packages.html5-parser
    pkgs.checkSSLCert
    pkgs.haskellPackages.csv-sip
    pkgs.emacsPackages.css-comb
    pkgs.haskellPackages.css-easings
    pkgs.python310Packages.cssselect2
    pkgs.python39Packages.cssutils
    pkgs.python39Packages.cssselect
    pkgs.emacsPackages.css-autoprefixer
    pkgs.python310Packages.css-parser
    pkgs.python310Packages.cssmin
    pkgs.nodePackages_latest.csslint
    pkgs.haskellPackages.css-text
    pkgs.haskellPackages.css-simple
    pkgs.python310Packages.cssselect
    pkgs.emacsPackages.css-eldoc
    pkgs.haskellPackages.css-syntax
    pkgs.python39Packages.csscompressor
    pkgs.python310Packages.css-html-js-minify
    pkgs.python39Packages.css-html-js-minify
    pkgs.nodePackages.csslint
    pkgs.python310Packages.cssutils
    pkgs.python39Packages.cssselect2
    pkgs.python39Packages.css-parser
    pkgs.emacsPackages.cssh
    pkgs.csslint
    pkgs.haskellPackages.css-selectors
    pkgs.css-html-js-minify
    pkgs.python39Packages.cssmin
    pkgs.python310Packages.csscompressor
    pkgs.haskellPackages.css
    pkgs.nodePackages.vscode-langservers-extracted
    pkgs.nodePackages.typescript-language-server  
  ];
}